@rootUrl = http://localhost:8080

post {{rootUrl}}/register
Content-Type: application/json

{
  "last_name": "Watson",
  "age": "32",
  "password": "sherlocked"
}

###
get {{rootUrl}}/foods  
  
###
get {{rootUrl}}/users

###
get {{rootUrl}}/movies/1234

###
post {{rootUrl}}/malumot
Content-Type: application/json
[
  {
  "id" : 01,
  "month": "September",
  "amount": 450000
},
{
  "id" : 02,
  "month": "May",
  "amount": 210000
},
{
  "id" : 03,
  "month": "July",
  "amount": 3100000
}
]
 
###
put {{rootUrl}}/expenses
Content-Type: application/json

{
  "id": 1,
  "name": "Anvar",
  "password": 1222 
}

###
delete {{rootUrl}}/expenses
  {
    "id": "i9i",
    "month": "Nokia 8800",
    "amount": 200
  }